version: "3.8"

services:
  catcar-wash-frontend:
    build:
      context: ./catcar_wash_service_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Build and start the frontend
# docker-compose -f docker-compose.frontend.yml up --build

# Run in background
# docker-compose -f docker-compose.frontend.yml up -d --build
