version: "3.8"

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    container_name: catcar_wash_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: catcar_wash_db
      POSTGRES_USER: catcar_wash_user
      POSTGRES_PASSWORD: catcar_wash_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - catcar_wash_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catcar_wash_user -d catcar_wash_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: catcar_wash_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@catcarwash.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - catcar_wash_network
    depends_on:
      postgres:
        condition: service_healthy

  # EMQX MQTT Broker (MQTT + WebSocket + Dashboard)
  emqx:
    image: emqx/emqx:5.6
    container_name: catcar_wash_emqx
    restart: unless-stopped
    ports:
      - "1883:1883" # MQTT TCP
      - "8083:8083" # MQTT over WebSocket
      - "18083:18083" # EMQX Dashboard
    environment:
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=admin123
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    networks:
      - catcar_wash_network

  # Backend Service (NestJS + Prisma)
  # backend:
  #   build:
  #     context: ./catcar_wash_service_serve
  #     dockerfile: Dockerfile
  #   container_name: catcar_wash_backend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000
  #     - API_PREFIX=api
  #     - VERSION=1.0.0
  #     - LOG_LEVEL=debug

  #     - DATABASE_URL=postgresql://catcar_wash_user:catcar_wash_password@postgres:5432/catcar_wash_db

  #     - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
  #     - JWT_EXPIRES_IN=24h

  #     - BEAM_API_URL=https://playground.api.beamcheckout.com
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - catcar_wash_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  emqx_data:
    driver: local
  emqx_log:
    driver: local

networks:
  catcar_wash_network:
    driver: bridge
# HOW TO RUN
# docker-compose -f docker-compose.develop.yml up --build
