export interface SalesRecord {
  timestamp: Date
  serviceName: string
  serviceType: string
  moneyReceived: number
  deviceId: string
}

export const useSalesData = () => {
  const salesData = ref<SalesRecord[]>([
    {
      timestamp: new Date("2024-08-24T14:30:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-001",
    },
    {
      timestamp: new Date("2024-08-24T14:25:00"),
      serviceName: "ล้างรถยนต์พรีเมียม",
      serviceType: "พรีเมียม",
      moneyReceived: 80,
      deviceId: "WASH-002",
    },
    {
      timestamp: new Date("2024-08-24T14:20:00"),
      serviceName: "ล้างรถจักรยานยนต์",
      serviceType: "จักรยานยนต์",
      moneyReceived: 20,
      deviceId: "WASH-003",
    },
    {
      timestamp: new Date("2024-08-24T14:15:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-001",
    },
    {
      timestamp: new Date("2024-08-24T14:10:00"),
      serviceName: "ล้างรถยนต์ดีลักซ์",
      serviceType: "ดีลักซ์",
      moneyReceived: 60,
      deviceId: "WASH-004",
    },
    {
      timestamp: new Date("2024-08-24T14:05:00"),
      serviceName: "ล้างรถจักรยานยนต์",
      serviceType: "จักรยานยนต์",
      moneyReceived: 20,
      deviceId: "WASH-003",
    },
    {
      timestamp: new Date("2024-08-24T14:00:00"),
      serviceName: "ล้างรถยนต์พรีเมียม",
      serviceType: "พรีเมียม",
      moneyReceived: 80,
      deviceId: "WASH-002",
    },
    {
      timestamp: new Date("2024-08-24T13:55:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-005",
    },
    {
      timestamp: new Date("2024-08-24T13:50:00"),
      serviceName: "ล้างรถยนต์ดีลักซ์",
      serviceType: "ดีลักซ์",
      moneyReceived: 60,
      deviceId: "WASH-001",
    },
    {
      timestamp: new Date("2024-08-24T13:45:00"),
      serviceName: "ล้างรถจักรยานยนต์",
      serviceType: "จักรยานยนต์",
      moneyReceived: 20,
      deviceId: "WASH-002",
    },
    {
      timestamp: new Date("2024-08-24T13:40:00"),
      serviceName: "ล้างรถยนต์พรีเมียม",
      serviceType: "พรีเมียม",
      moneyReceived: 80,
      deviceId: "WASH-003",
    },
    {
      timestamp: new Date("2024-08-24T13:35:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-004",
    },
    {
      timestamp: new Date("2024-08-24T13:30:00"),
      serviceName: "ล้างรถจักรยานยนต์",
      serviceType: "จักรยานยนต์",
      moneyReceived: 20,
      deviceId: "WASH-005",
    },
    {
      timestamp: new Date("2024-08-24T13:25:00"),
      serviceName: "ล้างรถยนต์ดีลักซ์",
      serviceType: "ดีลักซ์",
      moneyReceived: 60,
      deviceId: "WASH-001",
    },
    {
      timestamp: new Date("2024-08-24T13:20:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-002",
    },
    {
      timestamp: new Date("2024-08-24T13:15:00"),
      serviceName: "ล้างรถยนต์พรีเมียม",
      serviceType: "พรีเมียม",
      moneyReceived: 80,
      deviceId: "WASH-003",
    },
    {
      timestamp: new Date("2024-08-24T13:10:00"),
      serviceName: "ล้างรถจักรยานยนต์",
      serviceType: "จักรยานยนต์",
      moneyReceived: 20,
      deviceId: "WASH-004",
    },
    {
      timestamp: new Date("2024-08-24T13:05:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-005",
    },
    {
      timestamp: new Date("2024-08-24T13:00:00"),
      serviceName: "ล้างรถยนต์ดีลักซ์",
      serviceType: "ดีลักซ์",
      moneyReceived: 60,
      deviceId: "WASH-001",
    },
    {
      timestamp: new Date("2024-08-24T12:55:00"),
      serviceName: "ล้างรถยนต์พรีเมียม",
      serviceType: "พรีเมียม",
      moneyReceived: 80,
      deviceId: "WASH-002",
    },
    {
      timestamp: new Date("2024-08-24T12:50:00"),
      serviceName: "ล้างรถจักรยานยนต์",
      serviceType: "จักรยานยนต์",
      moneyReceived: 20,
      deviceId: "WASH-003",
    },
    {
      timestamp: new Date("2024-08-24T12:45:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-004",
    },
    {
      timestamp: new Date("2024-08-24T12:40:00"),
      serviceName: "ล้างรถยนต์ดีลักซ์",
      serviceType: "ดีลักซ์",
      moneyReceived: 60,
      deviceId: "WASH-005",
    },
    {
      timestamp: new Date("2024-08-24T12:35:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-001",
    },
    {
      timestamp: new Date("2024-08-24T12:30:00"),
      serviceName: "ล้างรถยนต์พรีเมียม",
      serviceType: "พรีเมียม",
      moneyReceived: 80,
      deviceId: "WASH-002",
    },
    {
      timestamp: new Date("2024-08-24T12:25:00"),
      serviceName: "ล้างรถจักรยานยนต์",
      serviceType: "จักรยานยนต์",
      moneyReceived: 20,
      deviceId: "WASH-003",
    },
    {
      timestamp: new Date("2024-08-24T12:20:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-004",
    },
    {
      timestamp: new Date("2024-08-24T12:15:00"),
      serviceName: "ล้างรถยนต์ดีลักซ์",
      serviceType: "ดีลักซ์",
      moneyReceived: 60,
      deviceId: "WASH-005",
    },
    {
      timestamp: new Date("2024-08-24T12:10:00"),
      serviceName: "ล้างรถยนต์พรีเมียม",
      serviceType: "พรีเมียม",
      moneyReceived: 80,
      deviceId: "WASH-001",
    },
    {
      timestamp: new Date("2024-08-24T12:05:00"),
      serviceName: "ล้างรถจักรยานยนต์",
      serviceType: "จักรยานยนต์",
      moneyReceived: 20,
      deviceId: "WASH-002",
    },
    {
      timestamp: new Date("2024-08-24T12:00:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-003",
    },
    {
      timestamp: new Date("2024-08-24T11:55:00"),
      serviceName: "ล้างรถยนต์ดีลักซ์",
      serviceType: "ดีลักซ์",
      moneyReceived: 60,
      deviceId: "WASH-004",
    },
    {
      timestamp: new Date("2024-08-24T11:50:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-005",
    },
    {
      timestamp: new Date("2024-08-24T11:45:00"),
      serviceName: "ล้างรถยนต์พรีเมียม",
      serviceType: "พรีเมียม",
      moneyReceived: 80,
      deviceId: "WASH-001",
    },
    {
      timestamp: new Date("2024-08-24T11:40:00"),
      serviceName: "ล้างรถจักรยานยนต์",
      serviceType: "จักรยานยนต์",
      moneyReceived: 20,
      deviceId: "WASH-002",
    },
    {
      timestamp: new Date("2024-08-24T11:35:00"),
      serviceName: "ล้างรถยนต์เบสิก",
      serviceType: "เบสิก",
      moneyReceived: 40,
      deviceId: "WASH-003",
    },
    {
      timestamp: new Date("2024-08-24T11:30:00"),
      serviceName: "ล้างรถยนต์ดีลักซ์",
      serviceType: "ดีลักซ์",
      moneyReceived: 60,
      deviceId: "WASH-004",
    },
    {
      timestamp: new Date("2024-08-24T11:25:00"),
      serviceName: "ล้างรถยนต์พรีเมียม",
      serviceType: "พรีเมียม",
      moneyReceived: 80,
      deviceId: "WASH-005",
    },
    {
      timestamp: new Date("2024-08-24T11:20:00"),
      serviceName: "ล้างรถจักรยานยนต์",
      serviceType: "จักรยานยนต์",
      moneyReceived: 20,
      deviceId: "WASH-001",
    },
  ]);

  return {
    salesData: readonly(salesData)
  }
}